bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('new', views.new, name='new'),
    path('create', views.create, name='create'),
    path('<int:id>/edit', views.edit, name='edit'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('bbs/', include('bbs.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/bbs/')),
]

bbs/models.py
from django.db import models

class Article(models.Model):
    content = models.CharField(max_length=200)
    user_name = models.CharField(max_length=200, null = True)

    def __str__(self):
        return self.content

bbs/forms.py
from django import forms
from .models import Article

class SearchForm(forms.Form):
        keyword = forms.CharField(label='検索', max_length=100)

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('content', 'user_name')

bbs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article
from .forms import SearchForm
from .forms import ArticleForm

def index(request):
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        keyword = searchForm.cleaned_data['keyword']
        articles = Article.objects.filter(content__contains=keyword)
    else:
        searchForm = SearchForm()
        articles = Article.objects.all()

    context = {
        'message': 'Hello Django',
        'articles': articles,
        'searchForm': searchForm,
    }
    return render(request, 'bbs/index.html', context)

def detail(request, id):
    article = get_object_or_404(Article, pk=id)
    context = {
      'message': 'Show Article' + str(id),
      'article': article,
    }
    return render(request, 'bbs/detail.html', context)

def new(request):
  articleForm = ArticleForm()

  context = {
    'message': 'New Article',
    'articleForm': articleForm,
  }
  return render(request, 'bbs/new.html', context)

def create(request):
    if request.method == 'POST':
        articleForm = ArticleForm(request.POST)
        if articleForm.is_valid():
            article = articleForm.save()

    context = {
        'message': 'Create article ' + str(article.id),
        'article': article,
    }
    return render(request, 'bbs/detail.html', context)

def edit(request, id):
    article = get_object_or_404(Article, pk=id)
    articleForm = ArticleForm(instance=article)

    context = {
        'message': 'Edit Article',
        'article': article,
        'articleForm': articleForm,
    }
    return render(request, 'bbs/edit.html', context)

def update(request, id):
  if request.method == 'POST':
    article = get_object_or_404(Article, pk=id)
    articleForm = ArticleForm(request.POST, instance=article)
    if articleForm.is_valid():
      articleForm.save()

    context = {
        'message': 'Update Article' + str(id),
        'article': article,
    }
    return render(request, 'bbs/detail.html', context)

def delete(request, id):
    article = get_object_or_404(Article, pk=id)
    article.delete()

    articles = Article.objects.all()
    context = {
        'message': 'Delete article ' + str(id),
        'articles': articles,
    }
    return render(request, 'bbs/index.html', context)

bbs/templates/bbs/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <title>paiza bbs</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <style>body {padding-top: 80px}</style>
  </head>
  <body>
    <nav class='navbar navbar-expand-md navbar-dark bg-dark fixed-top'>
      <a class='navbar-brand' href='{% url "bbs:index" %}'>paiza bbs</a>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

bbs/templates/bbs/detail.html
{% extends './base.html' %}
{% block content %}
    <h1>paiza bbs</h1>
    <p>{{ message }}</p>
    <p>{{ article.content }},{{user_name }}</p>
    <div>
      <a href='{% url "bbs:index" %}' class='btn btn-outline-primary'>一覧</a>
      <a href='{% url "bbs:edit" article.id %}' class='btn btn-outline-primary'>編集</a>
      <a href='{% url "bbs:delete" article.id %}' class='btn btn-outline-secondary'>削除</a>
    </div>
{% endblock %}

bbs/templates/bbs/edit.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>{{ message }}</h1>

    <form action='{% url "bbs:update" article.id %}' method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form articleForm layout='horizontal' %}
        <button type='submit' class='btn btn-outline-primary'>保存する</button>
        <a href='{% url "bbs:detail" article.id %}' class='btn btn-outline-secondary'>戻る</a>
    </form>
{% endblock %}

bbs/templates/bbs/index.html
{% extends './base.html' %}
{% block content %}
    <h1>paiza bbs</h1>
    <p>{{ message }}</p>

    {% if searchForm %}
      <form action='{% url "bbs:index" %}' method='get'>
        <div class='form-group'>
          {{ searchForm}}
          <input type="submit" class="btn btn-outline-primary" value="OK">
          <a href="{% url 'bbs:index' %}" class="btn-outline-secondery">クリア</a>
        </div>
      </form>
    {% endif %}

    <table class='table table-striped table-hover'>
      {% for article in articles %}
        <tr>
            <td>{{ article.content }}</td>
            <td>{{ article.user_name }}</td>
            <td>
              <a href='{% url "bbs:detail" article.id %}' class='btn btn-outline-primary'>詳細</a>
            </td>
        </tr>
      {% endfor %}
    </table>
    <p>
      <a href='{% url "bbs:new" %}' class='btn btn-outline-primary'>新規</a>
    </p>
{% endblock %}

bbs/templates/bbs/new.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block content %}
  <h1>{{ message }}</h1>

  <form action='{% url "bbs:create" %}' method='post' class='form'>
    {% csrf_token %}
    {% bootstrap_form articleForm layout='horizontal' %}
    <button type="submit" class="btn btn-outline-primary">作成する</button>
    <a href='{% url "bbs:index" %}' class="btn btn-outline-secondary">戻る</a>
  </form>
{% endblock %}